---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#


###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 808            # Line length
MD014: false
MD024: false
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD028: false
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
# MD034: false
MD036: false                  # Emphasis used instead of a heading
# MD040: false

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines

##########################
## Custom Rules Section ##
##########################
custom_rules:
  # Path to custom rule scripts
  - path: './custom-rules/todo-rule.js'  # Add the path to your custom rule file

##########################
## Enable custom rules ##
##########################
rules:
  # Enable your custom rules by name
  'custom-rule-todo': true  # The name of your custom rule
